### ISSUE TITLE
Font definition files 

### ISSUE THREAD

**Issue by ConvergedVentures** [Michadelic/CustomFontsSAC#3]
Any chance sap can host the font definition file (style sheet). The more security conscious won’t connect to the repository. 

Also the font files link don’t all work. 

Thanks

**Comment by Michadelic** [comment]
Hi @ConvergedVentures, thanks for opening this issue and the feedback.
Meanwhile, this is a standard feature and UI5 hosts the font file directly in their distrubution.

Instead of linking my repository for demo purposes, please do configure this URL in SAC:
https://ui5.sap.com/resources/sap/ui/core/themes/base/SAP-icons.css

This is the official UI5 CDN distribution, so it is a trusted source from SAP.

Hope that helps!

Michael
